# File: .github/workflows/workflow.yml

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Setup Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: "Install dependencies"
        run: |
          yarn install
      - name: "Building project"
        run: |
          yarn build
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "SneakGeek-Dev"
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
