product-request:
  post:
    tags:
      - product-request
    summary: Request product
    description: ""
    operationId: requestProduct
    parameters:
      - in: body
        name: body
        description: Product request information
        required: true
        schema:
          type: object
          required:
            - title
            - brand
          properties:
            title:
              type: string
            brand:
              $ref: "../definitions/constants.yaml#ShoeBrand"
            gender:
              $ref: "../definitions/constants.yaml#Gender"
            size:
              type: string
            condition:
              type: string
            colorways:
              type: array
              items:
                type: string
            imageUrls:
              type: array
              items:
                type: string
                format: url
