export const strings = {
  SignIn: 'Đăng nhập',
  SignUp: 'Đăng kí tài khoản',
  ContinueFacebook: 'Tiếp tục với Facebook',
  ContinueGoogle: 'Tiếp tục với Google',
  ContinueApple: 'Tiếp tục với Apple',
  SignUpEmail: 'Đăng kí bằng email',
  EmailRegisteredEng: 'This email has been registered.',
  EmailRegisteredVN:
    'Tài khoản với email này đã tồn tại. Xin vui lòng đăng nhập.',
  MemberAlready: 'Đã đăng kí bằng email?',
  Email: 'Email của bạn',
  Password: 'Mật khẩu',
  EmailNotFound: 'Email không tìm thấy. Xin vui lòng đăng ký.',
  ReenterPassword: 'Mật khẩu chưa chính xác. Xin vui lòng thử lại.',
  Passcode: 'Mã Code',
  ForgotPassword: 'Quên mật khẩu',
  InvalidLogin: 'Email hoặc mật khẩu không đúng',
  GoogleString: 'google',
  FacebookString: 'facebook',
  EmailString: 'email',
  EmailStringCap: 'Email',
  AccountCreatedByEmail:
    'Bạn đã tạo tài khoản bằng email. Xin vui lòng ấn đăng nhập.',
  AccountCreatedByGoogle:
    'Bạn đã tạo tài khoản bằng Google. Xin vui lòng tiếp tục với Google.',
  AccountCreatedByFacebook:
    'Bạn đã tạo tài khoản bằng Facebook. Xin vui lòng tiếp tục với Facebook.',
  FillInEmail:
    'Để khôi phục lại mật khẩu, bạn cần điền địa chỉ email của tài khoản đăng nhập:',
  ForgotPasswordTokenVerification:
    'Email chứa mã code để đặt lại mật khẩu đã được gửi đến hòm thư của bạn.',
  FillInPasscode: 'Nhập mã code trong email của bạn vào đây:',
  FillInPassword: 'Điền mật khẩu mới cho tài khoản của bạn:',
  ResetPasswordVerificationError: 'Mã xác thực không chính xác.',
  UnmatchedPasswords: 'Mật khẩu không trùng khớp.',
  PasswordResetSuccess: 'Thay đổi mật khẩu thành công.',
  NotEmailType: 'Hãy điền lại email.',
  InvalidPasswordErrorType1:
    'Mật khẩu cần ít nhất 8 ký tự, trong đó có ít nhất 1 chữ và 1 chữ số.',
  InvalidPasswordErrorType2:
    'Mật khẩu cần ít nhất 8 ký tự, trong đó có ít nhất 1 chữ, 1 số và 1 ký tự đặc biệt.',
  InvalidPasswordErrorType3:
    'Mật khẩu cần ít nhất 8 ký tự, trong đó có ít nhất 1 chữ in hoa, 1 chữ in thường, và 1 chữ số.',
  InvalidPasswordErrorType4:
    'Mật khẩu cần ít nhất 8 ký tự, trong đó có ít nhất 1 chữ in hoa, 1 chữ in thường, 1 chữ số, và 1 ký tự đặc biệt.',
  InvalidPasswordErrorType5:
    'Mật khẩu cần ít nhất 10 ký tự, trong đó có ít nhất 1 chữ in hoa, 1 chữ in thường, 1 chữ số, và 1 ký tự đặc biệt.',
  TermsOfServiceAgreement:
    'Khi đăng nhập, bạn đã đồng ý với điều khoản sử dụng của chúng tôi',
  SeeMore: 'Xem thêm',
  Notification: 'Thông báo',
  HomeTab: 'Trang chủ',
  SearchTab: 'Tìm kiếm',
  TransactionTab: 'Giao dịch',
  UserTab: 'Tài khoản',
  AccountInfo: 'Thông tin cá nhân',
  PaymentInfo: 'Thông tin thanh toán',
  AccountBalanceAmount: 'Số dư ví SneakGeek hiện tại của bạn là:',
  Amount: 'Số tiền',
  Bank: 'Ngân hàng',
  AccountNumber: 'Số tài khoản',
  AccountHolderName: 'Tên chủ tài khoản',
  NotificationSettings: 'Cài đặt thông báo',
  ShareApplication: 'Chia sẻ ứng dụng',
  InfoAppSetting: 'Các câu hỏi thường gặp',
  AppContact: 'Liên hệ',
  LogOut: 'Đăng xuất',
  HomeTabTitle: 'Trang chủ',
  TakePicture: 'Chụp ảnh',
  Cancel: 'Huỷ',
  Processing: 'Đang xử lý',
  ChoosePictureLocal: 'Chọn ảnh từ thư viện',
  ProductDetail: 'Chi tiết sản phẩm',
  ProductName: 'Tên sản phẩm',
  AllReviews: 'Tất cả đánh giá',
  Colorway: 'Màu chủ đạo',
  Brand: 'Hãng',
  Category: 'Phân khúc',
  NoReview: 'Hiện tại chưa có đánh giá nào.',
  Rating: 'Đánh giá sản phẩm',
  ReleaseDate: 'Ngày ra mắt',
  RetailPrice: 'Giá bán lẻ',
  NewReview: 'Đánh giá mới',
  RatingTitle: 'Đánh giá:',
  RatingPlaceHolder: 'Giày đi êm chân, dáng đẹp,...',
  Detail: 'Chi tiết:',
  PostRating: 'Đăng đánh giá',
  MissingInfoForReview:
    'Bạn cần thêm thông tin cá nhân trước khi đánh giá sản phẩm',
  AddInfoForReview: 'Thêm thông tin',
  PleaseWait: 'Xin chờ',
  NewSell: 'Bán sản phẩm',
  Sell: 'Bán',
  Deposit: 'Chuyển khoản',
  NewBuyOrder: 'Đăng mua sản phẩm',
  Continue: 'Tiếp tục',
  Withdraw: 'Rút tiền',
  SellShoe: 'Đăng bán',
  BuyShoe: 'Mua sản phẩm',
  CreateBuyOrder: 'Đặt mua sản phẩm',
  RelatedProducts: 'Sản phẩm liên quan',
  ChooseSize: 'Chọn cỡ và giá',
  ErrorPleaseTryAgain: 'Đã có lỗi xảy ra, xin vui lòng thử lại',
  Error: 'Đã có lỗi xảy ra',
  AccountNotVerifieid: 'Tài khoản của bạn chưa được xác thực',
  MissingAddress: 'thiếu địa chỉ giao hàng',
  BuyNow: 'Mua ngay',
  SetBuyPrice: 'Giá đặt mua',
  Checkout: 'Thanh toán',
  BuyProduct: 'Mua sản phẩm',
  ShoeSize: 'Cỡ giày',
  Address: 'Địa chỉ',
  Receipient: 'Nguời nhận',
  ProductPrice: 'Giá sản phẩm',
  ShippingFee: 'Giá chuyển phát nhanh',
  TotalFee: 'Tổng chi phí',
  IntlPayment: 'Thanh toán quốc tế',
  DomesticPayment: 'Thanh toán nội địa',
  PaymentSuccess: 'Đã mua thành công sản phẩm',
  BuyHistory: 'Lịch sử mua',
  SellHistory: 'Lịch sử bán',
  History: 'Lịch sử',
  Selling: 'Đang bán',
  Buying: 'Đang mua',
  Pending: 'Chờ duyệt',
  Sold: 'Đã bán',
  Bought: 'Đã mua',
  Denied: 'Từ chối',
  Price: 'Giá',
  Condition: 'Tình trạng',
  SellOrderDetail: 'Chi tiết đơn bán',
  BuyOrderDetail: 'Chi tiết đơn mua',
  OrderDescription: 'Miêu tả đơn hàng',
  NewCondition: 'Mới',
  OldCondition: 'Cũ',
  Tainted: 'Ố vàng',
  OutsoleWorn: 'Đế mòn',
  OrderStatus: 'Tình trạng đơn hàng',
  CheckingStatus: 'Tình trạng kiểm duyệt',
  Transaction: 'Giao dịch',
  TransactionCanceled: 'Đơn hàng bị huỷ',
  TransactionPending: 'Đang xác nhận',
  Confirm: 'Xác nhận',
  TransactionProcessed: 'Đã thanh toán',
  ProductNotFound: 'Không tìm thấy sản phẩm bạn muốn?',
  RequestNewProduct: 'Yêu cầu sản phẩm',
  AddReview: 'Thêm đánh giá',
  SortByDate: 'Sắp xếp theo thời gian',
  NoRating: 'Chưa có đánh giá',
  Gender: 'Giới tính',
  Men: 'Nam',
  Women: 'Nữ',
  HighestBuyOrderPrice: 'Giá đặt mua cao nhất',
  BuyNowPrice: 'Giá mua ngay',
  HighestBuyOrderExplanation:
    'Dựa trên các đơn đặt mua trên thị trường, SneakGeek đưa ra giá đặt mua cao nhất để tham khảo',
  SetPrice: 'Đặt giá',
  SetSellPrice: 'Giá đặt bán',
  SetPriceSuccess: 'Đặt giá thành công',
  SellPrice: 'Giá bán',
  ProductPictures: 'Ảnh sản phẩm',
  ProductOtherDetail: 'Các chi tiết khác của sản phẩm',
  UpdateOrder: 'Cập nhật đơn hàng',
  CancelOrder: 'Huỷ đơn hàng',
  LowestSellOrderPrice: 'Giá đặt bán thấp nhất',
  PleaseLogin: 'Xin vui lòng đăng nhập',
  NoAccountPleastLogin:
    'Hiện nay bạn chưa đăng nhập. Xin vui lòng đăng nhập để sử dụng tính năng này',
  MoneyIsProcessing:
    'Tiền sẽ được chuyển vào tài khoản của bạn trong vòng 5 đến 10 ngày tới.',
  MoneyIsProcessingContactingWithSneakGeek:
    'Lệnh rút tiền đang được thực hiện. Xin vui lòng liên hệ với SneakGeek nếu bạn cần thay đổi thông tin thanh toán.',
  NoMoneyInSneakGeekWallet: 'Ví SneakGeek chưa có tiền.',
  CannotWithdrawalMoreThanCurrentBalance:
    'Số tiền rút ra không thể lớn hơn số tiền hiện có.',
  PleaseProvideAllInformation: 'Xin vui lòng điền đủ thông thin chuyển khoản.',
  InventoryQuantity: 'Số lượng'
};
