// !
// ! Copyright (c) 2019 - SneakGeek. All rights reserved
// !

export enum OrderStatus {
  FAILED = "FAILED",
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
}

export type OrderType = "BuyOrder" | "SellOrder";

export enum TrackingStatus {
  WAITING_FOR_BANK_TRANSFER = "WAITING_FOR_BANK_TRANSFER",
  RECEIVED_BANK_TRANSFER = "RECEIVED_BANK_TRANSFER",
  NOT_RECEIVED_BANK_TRANSFER = "NOT_RECEIVED_BANK_TRANSFER",
  NOTIFYING_SELLER = "NOTIFYING_SELLER",
  SELLER_APPROVED_ORDER = "SELLER_APPROVED_ORDER",
  SELLER_REJECTED_ORDER = "SELLER_REJECTED_ORDER",
  ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION = "ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION",
  SHOE_VERIFIED = "SHOE_VERIFIED",
  SHOE_UNQUALIFIED = "SHOE_UNQUALIFIED",
  DELIVERING_TO_BUYER = "DELIVERING_TO_BUYER",
  BUYER_RECEIVED = "BUYER_RECEIVED",
}

export const TrackingStatusOrdering: Map<TrackingStatus, TrackingStatus> = new Map<
  TrackingStatus,
  TrackingStatus
>([
  [TrackingStatus.RECEIVED_BANK_TRANSFER, TrackingStatus.WAITING_FOR_BANK_TRANSFER],
  [TrackingStatus.NOT_RECEIVED_BANK_TRANSFER, TrackingStatus.WAITING_FOR_BANK_TRANSFER],
  [TrackingStatus.NOTIFYING_SELLER, TrackingStatus.RECEIVED_BANK_TRANSFER],
  [TrackingStatus.SELLER_APPROVED_ORDER, TrackingStatus.NOTIFYING_SELLER],
  [TrackingStatus.SELLER_REJECTED_ORDER, TrackingStatus.NOTIFYING_SELLER],
  [
    TrackingStatus.ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION,
    TrackingStatus.SELLER_APPROVED_ORDER,
  ],
  [
    TrackingStatus.SHOE_VERIFIED,
    TrackingStatus.ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION,
  ],
  [
    TrackingStatus.SHOE_UNQUALIFIED,
    TrackingStatus.ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION,
  ],
  [TrackingStatus.DELIVERING_TO_BUYER, TrackingStatus.SHOE_VERIFIED],
  [TrackingStatus.BUYER_RECEIVED, TrackingStatus.DELIVERING_TO_BUYER],
]);

export enum PaymentMethod {
  BANK_TRANSFER = "BANK_TRANSFER",
}
