// !
// ! Copyright (c) 2019 - SneakGeek. All rights reserved
// !

export enum OrderStatus {
  FAILED = "FAILED",
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
}

export type OrderType = "BuyOrder" | "SellOrder";

export enum TrackingStatus {
  WAITING_FOR_BANK_TRANSFER = "WAITING_FOR_BANK_TRANSFER",
  RECEIVED_BANK_TRANSFER = "RECEIVED_BANK_TRANSFER",
  NOT_RECEIVED_BANK_TRANSFER = "NOT_RECEIVED_BANK_TRANSFER",
  NOTIFYING_SELLER = "NOTIFYING_SELLER",
  SELLER_APPROVED_ORDER = "SELLER_APPROVED_ORDER",
  SELLER_REJECTED_ORDER = "SELLER_REJECTED_ORDER",
  ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION = "ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION",
  SHOE_VERIFIED = "SHOE_VERIFIED",
  SHOE_UNQUALIFIED = "SHOE_UNQUALIFIED",
  DELIVERING_TO_BUYER = "DELIVERING_TO_BUYER",
  BUYER_RECEIVED = "BUYER_RECEIVED",
}

export const PreviousTrackingStatusMap = {
  RECEIVED_BANK_TRANSFER: "WAITING_FOR_BANK_TRANSFER",
  NOT_RECEIVED_BANK_TRANSFER: "WAITING_FOR_BANK_TRANSFER",
  NOTIFYING_SELLER: "RECEIVED_BANK_TRANSFER",
  SELLER_APPROVED_ORDER: "NOTIFYING_SELLER",
  SELLER_REJECTED_ORDER: "NOTIFYING_SELLER",
  ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION: "SELLER_APPROVED_ORDER",
  SHOE_VERIFIED: "ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION",
  SHOE_UNQUALIFIED: "ORDER_BEING_SENT_TO_SNKGK_FOR_AUTHENTICATION",
  DELIVERING_TO_BUYER: "SHOE_VERIFIED",
  BUYER_RECEIVED: "DELIVERING_TO_BUYER",
};

export enum PaymentMethod {
  BANK_TRANSFER = "BANK_TRANSFER",
}
