export enum OrderStatus {
  DENIED = "DENIED",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  COMPLETED = "COMPLETED"
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PROCESSED = "PROCESSED",
  CANCELED = "CANCELED"
}

export enum TrackingStatus {
  PENDING_PICKUP_FROM_SELLER = "PENDING_PICKUP_FROM_SELLER",
  DELIVERING_TO_SNEAKGEEK = "DELIVERING_TO_SNEAKGEEK",
  DELIVERED_TO_SNEAKGEEK = "DELIVERED_TO_SNEAKGEEK",
  APPROVED_BY_SNEAKGEEK = "APPROVED_BY_SNEAKGEEK",
  REJECTED_BY_SNEAKGEEK = "REJECTED_BY_SNEAKGEEK",
  PENDING_PICKUP_FROM_SNEAKGEEK = "PENDING_PICKUP_FROM_SNEAKGEEK",
  DELIVERING_TO_BUYER = "DELIVERING_TO_BUYER",
  DELIVERED_TO_BUYER = "DELIVERED_TO_BUYER"
}

export enum Gender {
  none = "none",
  men = "men",
  women = "women",
  unisex = "unisex",
  child = "child",
  toddler = "toddler",
  infant = "infant",
  preschool = "preschool"
}