runtime: nodejs12
liveness_check:
  path: "/api/v1/health"
  check_interval_sec: 60
  timeout_sec: 5
  failure_threshold: 5
  success_threshold: 2
automatic_scaling:
  min_idle_instances: 1
inbound_services:
  - warmup
