name: App staging deployment (auto)
on:
  push:
    branches:
    - main
    - feature/release-app-staging
    paths:
    - .github/workflows/app-auto-staging.yaml
    - client/app/**
    - client/business/**
jobs:
  appcenter_deploy:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: client/app
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Bump version number
        run: |
          cd ../../
          yarn install
          GIT_TAG=`node scripts/bump_version.js --type=app`
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
      - name: Get current version
        run: cat ../../version.json
      - name: Run fastlane to bump iOS version
        run: |
          IOS_VERSION_NUMBER=`node -e "const v=require('../../version.json');console.log(v.app.version)"`
          IOS_BUILD_NUMBER=`node -e "const v=require('../../version.json');console.log(v.app.build)"`
          fastlane ios bump_version_number
          fastlane ios bump_build_number
      - name: Archive for staging
        run: fastlane ios archive_staging
      - name: Distribute to AppCenter
        run: fastlane ios distribute_staging_app_center
      - name: Commit new version and tag after successful run
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: '.'
          default_author: github_actor
          push: true
          signoff: false
          tag: ${{ env.GIT_TAG }}
      