name: Backend service auto rollout (staging)
on:
  push:
    branches:
    - main
    paths:
    - service/**
    - .github/workflows/backend-auto-staging.yaml
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Bump version number
        run: |
          cd ../
          yarn install
          GIT_TAG=`node scripts/bump_version.js --type=service`
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Get current version
        run: |
          cat ../version.json
      - name: Commit new version and tag
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: '.'
          default_author: github_actor
          push: true
          signoff: false
          tag: ${{ env.GIT_TAG }}
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GAE_STAGING_SERVICE_ACCOUNT }}
          service_account_key: ${{ secrets.GAE_STAGING_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.STAGING_PROJECT_ID }}
      - name: Deploy to Google App Engine prod
        env:
          GAE_STAGING_SERVICE_ACCOUNT: ${{ secrets.GAE_STAGING_SERVICE_ACCOUNT }}
          STAGING_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
        run: |
          VERSION=`node -e "const v=require('../version.json');console.log(v.service.version+'-'+v.service.build)"`
          gcloud app deploy ./app-dev.yaml \
            --version=$VERSION \
            --no-cache --promote --verbosity=info --quiet \
            --account=$GAE_STAGING_SERVICE_ACCOUNT \
            --project=$STAGING_PROJECT_ID